package com.yzf.mapper;

import com.yzf.entity.Culture;
import com.yzf.entity.CultureExample;
import java.util.List;

import com.yzf.entity.Hislog;
import org.apache.ibatis.annotations.Param;

public interface CultureMapper {

    long countByExample(CultureExample example);


    int deleteByExample(CultureExample example);


    int deleteByPrimaryKey(Integer cid);

    Culture showinfo();

    int update(@Param("text") String text);

    int insert(Culture record);

    int insertSelective(Culture record);

    List<Hislog> showhisCul();

    List<Culture> selectByExampleWithBLOBs(CultureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table culture
     *
     * @mbg.generated Thu Oct 31 15:16:35 CST 2019
     */
    List<Culture> selectByExample(CultureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table culture
     *
     * @mbg.generated Thu Oct 31 15:16:35 CST 2019
     */
    Culture selectByPrimaryKey(Integer cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table culture
     *
     * @mbg.generated Thu Oct 31 15:16:35 CST 2019
     */
    int updateByExampleSelective(@Param("record") Culture record, @Param("example") CultureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table culture
     *
     * @mbg.generated Thu Oct 31 15:16:35 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") Culture record, @Param("example") CultureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table culture
     *
     * @mbg.generated Thu Oct 31 15:16:35 CST 2019
     */
    int updateByExample(@Param("record") Culture record, @Param("example") CultureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table culture
     *
     * @mbg.generated Thu Oct 31 15:16:35 CST 2019
     */
    int updateByPrimaryKeySelective(Culture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table culture
     *
     * @mbg.generated Thu Oct 31 15:16:35 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(Culture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table culture
     *
     * @mbg.generated Thu Oct 31 15:16:35 CST 2019
     */
    int updateByPrimaryKey(Culture record);
}