package com.yzf.mapper;

import com.yzf.entity.Culture;
import com.yzf.entity.Hislog;
import com.yzf.entity.HislogExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface HislogMapper {

    List<Hislog> showinfo();

    long countByExample(HislogExample example);

    Culture recoveryCul(Culture culture);

    int deleteByExample(HislogExample example);


    int deleteByPrimaryKey(Integer hid);


    int insert(Hislog record);

    int insert1(Hislog record);


    int insertSelective(Hislog record);


    List<Hislog> selectByExampleWithBLOBs(HislogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hislog
     *
     * @mbg.generated Fri Nov 01 21:14:30 CST 2019
     */
    List<Hislog> selectByExample(HislogExample example);


    Hislog selectByPrimaryKey(Integer hid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hislog
     *
     * @mbg.generated Fri Nov 01 21:14:30 CST 2019
     */
    int updateByExampleSelective(@Param("record") Hislog record, @Param("example") HislogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hislog
     *
     * @mbg.generated Fri Nov 01 21:14:30 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") Hislog record, @Param("example") HislogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hislog
     *
     * @mbg.generated Fri Nov 01 21:14:30 CST 2019
     */
    int updateByExample(@Param("record") Hislog record, @Param("example") HislogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hislog
     *
     * @mbg.generated Fri Nov 01 21:14:30 CST 2019
     */
    int updateByPrimaryKeySelective(Hislog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hislog
     *
     * @mbg.generated Fri Nov 01 21:14:30 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(Hislog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hislog
     *
     * @mbg.generated Fri Nov 01 21:14:30 CST 2019
     */
    int updateByPrimaryKey(Hislog record);
}