package com.yzf.entity;

public class contact {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contact.cid
     *
     * @mbg.generated Thu Oct 31 15:16:35 CST 2019
     */
    private Integer cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contact.cphone
     *
     * @mbg.generated Thu Oct 31 15:16:35 CST 2019
     */
    private String cphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contact.cfac
     *
     * @mbg.generated Thu Oct 31 15:16:35 CST 2019
     */
    private String cfac;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contact.cqq
     *
     * @mbg.generated Thu Oct 31 15:16:35 CST 2019
     */
    private String cqq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contact.cemail
     *
     * @mbg.generated Thu Oct 31 15:16:35 CST 2019
     */
    private String cemail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contact.chttps
     *
     * @mbg.generated Thu Oct 31 15:16:35 CST 2019
     */
    private String chttps;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contact.coperate
     *
     * @mbg.generated Thu Oct 31 15:16:35 CST 2019
     */
    private String coperate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contact.caddress
     *
     * @mbg.generated Thu Oct 31 15:16:35 CST 2019
     */
    private String caddress;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact.cid
     *
     * @return the value of contact.cid
     *
     * @mbg.generated Thu Oct 31 15:16:35 CST 2019
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact.cid
     *
     * @param cid the value for contact.cid
     *
     * @mbg.generated Thu Oct 31 15:16:35 CST 2019
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact.cphone
     *
     * @return the value of contact.cphone
     *
     * @mbg.generated Thu Oct 31 15:16:35 CST 2019
     */
    public String getCphone() {
        return cphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact.cphone
     *
     * @param cphone the value for contact.cphone
     *
     * @mbg.generated Thu Oct 31 15:16:35 CST 2019
     */
    public void setCphone(String cphone) {
        this.cphone = cphone == null ? null : cphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact.cfac
     *
     * @return the value of contact.cfac
     *
     * @mbg.generated Thu Oct 31 15:16:35 CST 2019
     */
    public String getCfac() {
        return cfac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact.cfac
     *
     * @param cfac the value for contact.cfac
     *
     * @mbg.generated Thu Oct 31 15:16:35 CST 2019
     */
    public void setCfac(String cfac) {
        this.cfac = cfac == null ? null : cfac.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact.cqq
     *
     * @return the value of contact.cqq
     *
     * @mbg.generated Thu Oct 31 15:16:35 CST 2019
     */
    public String getCqq() {
        return cqq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact.cqq
     *
     * @param cqq the value for contact.cqq
     *
     * @mbg.generated Thu Oct 31 15:16:35 CST 2019
     */
    public void setCqq(String cqq) {
        this.cqq = cqq == null ? null : cqq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact.cemail
     *
     * @return the value of contact.cemail
     *
     * @mbg.generated Thu Oct 31 15:16:35 CST 2019
     */
    public String getCemail() {
        return cemail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact.cemail
     *
     * @param cemail the value for contact.cemail
     *
     * @mbg.generated Thu Oct 31 15:16:35 CST 2019
     */
    public void setCemail(String cemail) {
        this.cemail = cemail == null ? null : cemail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact.chttps
     *
     * @return the value of contact.chttps
     *
     * @mbg.generated Thu Oct 31 15:16:35 CST 2019
     */
    public String getChttps() {
        return chttps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact.chttps
     *
     * @param chttps the value for contact.chttps
     *
     * @mbg.generated Thu Oct 31 15:16:35 CST 2019
     */
    public void setChttps(String chttps) {
        this.chttps = chttps == null ? null : chttps.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact.coperate
     *
     * @return the value of contact.coperate
     *
     * @mbg.generated Thu Oct 31 15:16:35 CST 2019
     */
    public String getCoperate() {
        return coperate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact.coperate
     *
     * @param coperate the value for contact.coperate
     *
     * @mbg.generated Thu Oct 31 15:16:35 CST 2019
     */
    public void setCoperate(String coperate) {
        this.coperate = coperate == null ? null : coperate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact.caddress
     *
     * @return the value of contact.caddress
     *
     * @mbg.generated Thu Oct 31 15:16:35 CST 2019
     */
    public String getCaddress() {
        return caddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact.caddress
     *
     * @param caddress the value for contact.caddress
     *
     * @mbg.generated Thu Oct 31 15:16:35 CST 2019
     */
    public void setCaddress(String caddress) {
        this.caddress = caddress == null ? null : caddress.trim();
    }
}