package com.yzf.entity;

public class DeptinfosWithBLOBs extends Deptinfos {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deptinfos.duty
     *
     * @mbg.generated Thu Oct 31 15:16:35 CST 2019
     */
    private String duty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deptinfos.demand
     *
     * @mbg.generated Thu Oct 31 15:16:35 CST 2019
     */
    private String demand;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deptinfos.duty
     *
     * @return the value of deptinfos.duty
     *
     * @mbg.generated Thu Oct 31 15:16:35 CST 2019
     */
    public String getDuty() {
        return duty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deptinfos.duty
     *
     * @param duty the value for deptinfos.duty
     *
     * @mbg.generated Thu Oct 31 15:16:35 CST 2019
     */
    public void setDuty(String duty) {
        this.duty = duty == null ? null : duty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deptinfos.demand
     *
     * @return the value of deptinfos.demand
     *
     * @mbg.generated Thu Oct 31 15:16:35 CST 2019
     */
    public String getDemand() {
        return demand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deptinfos.demand
     *
     * @param demand the value for deptinfos.demand
     *
     * @mbg.generated Thu Oct 31 15:16:35 CST 2019
     */
    public void setDemand(String demand) {
        this.demand = demand == null ? null : demand.trim();
    }
}