package com.yzf.entity;

import com.fasterxml.jackson.annotation.JsonFormat;
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.stereotype.Component;

import java.util.Date;
@Component
public class Hislog {

    private Integer hid;


    private String haddress;

    public String getHaddress() {
        return haddress;
    }

    public void setHaddress(String haddress) {
        this.haddress = haddress;
    }

    @JsonFormat(pattern = "yyyy-MM-dd ")
    private Date htime;

    private String hname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hislog.htype
     *
     * @mbg.generated Fri Nov 01 21:14:30 CST 2019
     */
    private Integer htype;


    private String htext;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hislog.hid
     *
     * @return the value of hislog.hid
     *
     * @mbg.generated Fri Nov 01 21:14:30 CST 2019
     */
    public Integer getHid() {
        return hid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hislog.hid
     *
     * @param hid the value for hislog.hid
     *
     * @mbg.generated Fri Nov 01 21:14:30 CST 2019
     */
    public void setHid(Integer hid) {
        this.hid = hid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hislog.htime
     *
     * @return the value of hislog.htime
     *
     * @mbg.generated Fri Nov 01 21:14:30 CST 2019
     */
    public Date getHtime() {
        return htime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hislog.htime
     *
     * @param htime the value for hislog.htime
     *
     * @mbg.generated Fri Nov 01 21:14:30 CST 2019
     */
    public void setHtime(Date htime) {
        this.htime = htime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hislog.hname
     *
     * @return the value of hislog.hname
     *
     * @mbg.generated Fri Nov 01 21:14:30 CST 2019
     */
    public String getHname() {
        return hname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hislog.hname
     *
     * @param hname the value for hislog.hname
     *
     * @mbg.generated Fri Nov 01 21:14:30 CST 2019
     */
    public void setHname(String hname) {
        this.hname = hname == null ? null : hname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hislog.htype
     *
     * @return the value of hislog.htype
     *
     * @mbg.generated Fri Nov 01 21:14:30 CST 2019
     */
    public Integer getHtype() {
        return htype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hislog.htype
     *
     * @param htype the value for hislog.htype
     *
     * @mbg.generated Fri Nov 01 21:14:30 CST 2019
     */
    public void setHtype(Integer htype) {
        this.htype = htype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hislog.htext
     *
     * @return the value of hislog.htext
     *
     * @mbg.generated Fri Nov 01 21:14:30 CST 2019
     */
    public String getHtext() {
        return htext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hislog.htext
     *
     * @param htext the value for hislog.htext
     *
     * @mbg.generated Fri Nov 01 21:14:30 CST 2019
     */
    public void setHtext(String htext) {
        this.htext = htext == null ? null : htext.trim();
    }
}