package com.yzf.entity;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;

public class History {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history.hid
     *
     * @mbg.generated Thu Oct 31 15:16:35 CST 2019
     */
    private Integer hid;

     @JsonFormat(pattern = "yyyy-MM-dd")
    private Date htime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history.htext
     *
     * @mbg.generated Thu Oct 31 15:16:35 CST 2019
     */
    private String htext;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history.hid
     *
     * @return the value of history.hid
     *
     * @mbg.generated Thu Oct 31 15:16:35 CST 2019
     */
    public Integer getHid() {
        return hid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history.hid
     *
     * @param hid the value for history.hid
     *
     * @mbg.generated Thu Oct 31 15:16:35 CST 2019
     */
    public void setHid(Integer hid) {
        this.hid = hid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history.htime
     *
     * @return the value of history.htime
     *
     * @mbg.generated Thu Oct 31 15:16:35 CST 2019
     */
    public Date getHtime() {
        return htime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history.htime
     *
     * @param htime the value for history.htime
     *
     * @mbg.generated Thu Oct 31 15:16:35 CST 2019
     */
    public void setHtime(Date htime) {
        this.htime = htime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history.htext
     *
     * @return the value of history.htext
     *
     * @mbg.generated Thu Oct 31 15:16:35 CST 2019
     */
    public String getHtext() {
        return htext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history.htext
     *
     * @param htext the value for history.htext
     *
     * @mbg.generated Thu Oct 31 15:16:35 CST 2019
     */
    public void setHtext(String htext) {
        this.htext = htext == null ? null : htext.trim();
    }
}