package com.yzf.entity;

import java.util.Date;

public class Log {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.lid
     *
     * @mbg.generated Thu Oct 31 15:16:35 CST 2019
     */
    private Integer lid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.ltime
     *
     * @mbg.generated Thu Oct 31 15:16:35 CST 2019
     */
    private Date ltime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.lperson
     *
     * @mbg.generated Thu Oct 31 15:16:35 CST 2019
     */
    private String lperson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.lname
     *
     * @mbg.generated Thu Oct 31 15:16:35 CST 2019
     */
    private String lname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.lid
     *
     * @return the value of log.lid
     *
     * @mbg.generated Thu Oct 31 15:16:35 CST 2019
     */
    public Integer getLid() {
        return lid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.lid
     *
     * @param lid the value for log.lid
     *
     * @mbg.generated Thu Oct 31 15:16:35 CST 2019
     */
    public void setLid(Integer lid) {
        this.lid = lid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.ltime
     *
     * @return the value of log.ltime
     *
     * @mbg.generated Thu Oct 31 15:16:35 CST 2019
     */
    public Date getLtime() {
        return ltime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.ltime
     *
     * @param ltime the value for log.ltime
     *
     * @mbg.generated Thu Oct 31 15:16:35 CST 2019
     */
    public void setLtime(Date ltime) {
        this.ltime = ltime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.lperson
     *
     * @return the value of log.lperson
     *
     * @mbg.generated Thu Oct 31 15:16:35 CST 2019
     */
    public String getLperson() {
        return lperson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.lperson
     *
     * @param lperson the value for log.lperson
     *
     * @mbg.generated Thu Oct 31 15:16:35 CST 2019
     */
    public void setLperson(String lperson) {
        this.lperson = lperson == null ? null : lperson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.lname
     *
     * @return the value of log.lname
     *
     * @mbg.generated Thu Oct 31 15:16:35 CST 2019
     */
    public String getLname() {
        return lname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.lname
     *
     * @param lname the value for log.lname
     *
     * @mbg.generated Thu Oct 31 15:16:35 CST 2019
     */
    public void setLname(String lname) {
        this.lname = lname == null ? null : lname.trim();
    }
}