package com.yzf.entity;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;

public class Project {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.pid
     *
     * @mbg.generated Thu Oct 31 15:16:35 CST 2019
     */
    private Integer pid;


    private String pimg;

    public String getPimg() {
        return pimg;
    }

    public void setPimg(String pimg) {
        this.pimg = pimg;
    }

    private String pname;

     @JsonFormat(pattern = "yyyy-MM-dd")
    private Date ptime;


    private Integer pnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.psource
     *
     * @mbg.generated Thu Oct 31 15:16:35 CST 2019
     */
    private String psource;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.ptext
     *
     * @mbg.generated Thu Oct 31 15:16:35 CST 2019
     */
    private String ptext;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.pid
     *
     * @return the value of project.pid
     *
     * @mbg.generated Thu Oct 31 15:16:35 CST 2019
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.pid
     *
     * @param pid the value for project.pid
     *
     * @mbg.generated Thu Oct 31 15:16:35 CST 2019
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.pname
     *
     * @return the value of project.pname
     *
     * @mbg.generated Thu Oct 31 15:16:35 CST 2019
     */
    public String getPname() {
        return pname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.pname
     *
     * @param pname the value for project.pname
     *
     * @mbg.generated Thu Oct 31 15:16:35 CST 2019
     */
    public void setPname(String pname) {
        this.pname = pname == null ? null : pname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.ptime
     *
     * @return the value of project.ptime
     *
     * @mbg.generated Thu Oct 31 15:16:35 CST 2019
     */
    public Date getPtime() {
        return ptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.ptime
     *
     * @param ptime the value for project.ptime
     *
     * @mbg.generated Thu Oct 31 15:16:35 CST 2019
     */
    public void setPtime(Date ptime) {
        this.ptime = ptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.pnum
     *
     * @return the value of project.pnum
     *
     * @mbg.generated Thu Oct 31 15:16:35 CST 2019
     */
    public Integer getPnum() {
        return pnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.pnum
     *
     * @param pnum the value for project.pnum
     *
     * @mbg.generated Thu Oct 31 15:16:35 CST 2019
     */
    public void setPnum(Integer pnum) {
        this.pnum = pnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.psource
     *
     * @return the value of project.psource
     *
     * @mbg.generated Thu Oct 31 15:16:35 CST 2019
     */
    public String getPsource() {
        return psource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.psource
     *
     * @param psource the value for project.psource
     *
     * @mbg.generated Thu Oct 31 15:16:35 CST 2019
     */
    public void setPsource(String psource) {
        this.psource = psource == null ? null : psource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.ptext
     *
     * @return the value of project.ptext
     *
     * @mbg.generated Thu Oct 31 15:16:35 CST 2019
     */
    public String getPtext() {
        return ptext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.ptext
     *
     * @param ptext the value for project.ptext
     *
     * @mbg.generated Thu Oct 31 15:16:35 CST 2019
     */
    public void setPtext(String ptext) {
        this.ptext = ptext == null ? null : ptext.trim();
    }
}