package com.yzf.entity;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;

public class Speak {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column speak.sid
     *
     * @mbg.generated Thu Oct 31 15:16:35 CST 2019
     */
    private Integer sid;

    @JsonFormat(pattern = "yyy-MM-dd")
    private Date stime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column speak.sname
     *
     * @mbg.generated Thu Oct 31 15:16:35 CST 2019
     */
    private String sname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column speak.stext
     *
     * @mbg.generated Thu Oct 31 15:16:35 CST 2019
     */
    private String stext;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column speak.sid
     *
     * @return the value of speak.sid
     *
     * @mbg.generated Thu Oct 31 15:16:35 CST 2019
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column speak.sid
     *
     * @param sid the value for speak.sid
     *
     * @mbg.generated Thu Oct 31 15:16:35 CST 2019
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column speak.stime
     *
     * @return the value of speak.stime
     *
     * @mbg.generated Thu Oct 31 15:16:35 CST 2019
     */
    public Date getStime() {
        return stime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column speak.stime
     *
     * @param stime the value for speak.stime
     *
     * @mbg.generated Thu Oct 31 15:16:35 CST 2019
     */
    public void setStime(Date stime) {
        this.stime = stime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column speak.sname
     *
     * @return the value of speak.sname
     *
     * @mbg.generated Thu Oct 31 15:16:35 CST 2019
     */
    public String getSname() {
        return sname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column speak.sname
     *
     * @param sname the value for speak.sname
     *
     * @mbg.generated Thu Oct 31 15:16:35 CST 2019
     */
    public void setSname(String sname) {
        this.sname = sname == null ? null : sname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column speak.stext
     *
     * @return the value of speak.stext
     *
     * @mbg.generated Thu Oct 31 15:16:35 CST 2019
     */
    public String getStext() {
        return stext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column speak.stext
     *
     * @param stext the value for speak.stext
     *
     * @mbg.generated Thu Oct 31 15:16:35 CST 2019
     */
    public void setStext(String stext) {
        this.stext = stext == null ? null : stext.trim();
    }
}